version: '3'
services:
  blog-app:
    image: hawkinswinja/blog_app:1.0.0
    depends_on:
      - redis
      - db
    ports:
      - '5000:5000'
  db:
    image: mongo:4
    expose:
      - '6379'
  redis:
     image: redis:alpine
     expose:
      - '27017'
